<?php

namespace Database\Seeders;

use App\Models\Kuliner;
use App\Models\Province;
use Illuminate\Database\Seeder;

class KulinerSeeder extends Seeder
{
    public function run(): void
    {
        $provinces = Province::all()->keyBy('id');
        
        $kulinerData = [
            ['province_id' => 1, 'name' => 'Mie Aceh', 'description' => 'Mie kuning tebal dengan bumbu rempah khas Aceh yang kaya rasa', 'price' => 25000, 'image' => 'images/kuliner/Mie Aceh.webp'],
            ['province_id' => 1, 'name' => 'Kue Bhoi', 'description' => 'Kue tradisional Aceh berbahan dasar kelapa', 'price' => 15000],
            ['province_id' => 1, 'name' => 'Kuah Pliek U', 'description' => 'Gulai dengan patarana (patarana adalah santan kering)', 'price' => 30000],
            ['province_id' => 1, 'name' => 'Kopi Gayo', 'description' => 'Kopi arabika khas dataran tinggi Gayo', 'price' => 15000, 'image' => 'images/kuliner/Kopi Gayo.jpg'],
            ['province_id' => 2, 'name' => 'Saksang', 'description' => 'Masakan daging babi khas Batak dengan bumbu andaliman', 'price' => 35000, 'image' => 'images/kuliner/Saksang.jpg'],
            ['province_id' => 2, 'name' => 'Bika Ambon', 'description' => 'Kue bersarang khas Medan yang lembut dan manis', 'price' => 40000, 'image' => 'images/kuliner/Bika Ambon.jpg'],
            ['province_id' => 2, 'name' => 'Arsik', 'description' => 'Ikan mas bumbu khas Batak Toba yang pedas', 'price' => 45000, 'image' => 'images/kuliner/Arsik.webp'],
            ['province_id' => 2, 'name' => 'Ikan Asap Danau', 'description' => 'Ikan asap khas Danau Toba', 'price' => 35000, 'image' => 'images/kuliner/Ikan Asap Danau.jpeg'],
            ['province_id' => 3, 'name' => 'Rendang', 'description' => 'Daging sapi bumbu rempah kental, makanan terenak di dunia', 'price' => 50000, 'image' => 'images/kuliner/rendang_1767529778.png'],
            ['province_id' => 3, 'name' => 'Sate Padang', 'description' => 'Sate dengan kuah khas Padang yang kental', 'price' => 30000, 'image' => 'images/tradisi/Makan Bajamba.webp'],
            ['province_id' => 3, 'name' => 'Dendeng Balado', 'description' => 'Daging iris tipis digoreng dengan sambal balado', 'price' => 60000, 'image' => 'images/kuliner/Dendeng Balado.jpg'],
            ['province_id' => 4, 'name' => 'Gulai Belacan', 'description' => 'Ikan dengan kuah terasi khas Riau', 'price' => 35000],
            ['province_id' => 4, 'name' => 'Asam Pedas', 'description' => 'Ikan dengan kuah asam pedas yang segar', 'price' => 40000],
            ['province_id' => 4, 'name' => 'Bolu Kemojo', 'description' => 'Kue bolu khas Riau yang lembut', 'price' => 25000],
            ['province_id' => 5, 'name' => 'Tempoyak', 'description' => 'Sambal dari durian yang difermentasi', 'price' => 20000, 'image' => 'images/wisata/Tempoyak Patin.jpg'],
            ['province_id' => 5, 'name' => 'Gulai Ikan Patin', 'description' => 'Ikan patin dengan kuah kuning khas Jambi', 'price' => 45000, 'image' => 'images/kuliner/Gulai-Ikan-Patin.jpeg'],
            ['province_id' => 5, 'name' => 'Kue Padamaran', 'description' => 'Kue tradisional berbentuk bunga', 'price' => 15000],
            ['province_id' => 6, 'name' => 'Pempek', 'description' => 'Olahan ikan tenggiri dengan cuko yang asam pedas', 'price' => 25000, 'image' => 'images/kuliner/pempek_palembang_1767578246.png'],
            ['province_id' => 6, 'name' => 'Tekwan', 'description' => 'Sup pempek dengan taburan daun bawang', 'price' => 20000],
            ['province_id' => 6, 'name' => 'Model', 'description' => 'Pempek isi tahu dengan kuah sup yang gurih', 'price' => 20000, 'image' => 'images/kuliner/model.webp'],
            ['province_id' => 6, 'name' => 'Kemplang', 'description' => 'Kerupuk ikan kering yang renyah', 'price' => 30000],
            ['province_id' => 7, 'name' => 'Pendap', 'description' => 'Ikan mas bumbu kuning dibungkus daun talas', 'price' => 35000],
            ['province_id' => 7, 'name' => 'Bagar Hiu', 'description' => 'Gulai ikan hiu khas Bengkulu', 'price' => 40000],
            ['province_id' => 7, 'name' => 'Lemang', 'description' => 'Ketan dimasak dalam bambu dengan santan', 'price' => 20000],
            ['province_id' => 8, 'name' => 'Seruit', 'description' => 'Ikan bakar dengan sambal terasi dan lalapan', 'price' => 30000],
            ['province_id' => 8, 'name' => 'Pindang Tulang', 'description' => 'Sup ikan patin dengan bumbu khas Lampung', 'price' => 40000],
            ['province_id' => 8, 'name' => 'Kemplang', 'description' => 'Kerupuk ikan khas Lampung', 'price' => 25000],
            ['province_id' => 9, 'name' => 'Mie Belitung', 'description' => 'Mie dengan tauco dan seafood segar', 'price' => 30000],
            ['province_id' => 9, 'name' => 'Lempah Kuning', 'description' => 'Ikan dengan kuah kuning bumbu rempah', 'price' => 35000],
            ['province_id' => 9, 'name' => 'Makan Bedulang', 'description' => 'Tradisi makan bersama dalam satu nampan khas Babel', 'price' => 100000, 'image' => 'images/tradisi/makan_bedulang.png'],
            ['province_id' => 9, 'name' => 'Kue Berendam', 'description' => 'Kue basah khas Bangka yang kenyal', 'price' => 15000],
            ['province_id' => 10, 'name' => 'Gonggong', 'description' => 'Siput laut yang direbus, seafood khas Batam', 'price' => 40000],
            ['province_id' => 10, 'name' => 'Otak-Otak', 'description' => 'Adonan ikan dibungkus daun nipah lalu dibakar', 'price' => 25000, 'image' => 'images/kuliner/otak_otak_tanjung_pinang.png'],
            ['province_id' => 10, 'name' => 'Gong-Gong Sambal', 'description' => 'Gonggong dengan sambal pedas', 'price' => 45000],
            ['province_id' => 11, 'name' => 'Kerak Telor', 'description' => 'Omelet khas Betawi dengan kelapa sangrai', 'price' => 25000],
            ['province_id' => 11, 'name' => 'Soto Betawi', 'description' => 'Soto santan dengan daging sapi dan jeroan', 'price' => 30000],
            ['province_id' => 11, 'name' => 'Nasi Goreng', 'description' => 'Nasi goreng spesial dengan telur dan kerupuk', 'price' => 20000, 'image' => 'images/kuliner/nasi_goreng_1767529778.png'],
            ['province_id' => 11, 'name' => 'Nasi Uduk', 'description' => 'Nasi gurih khas Jakarta', 'price' => 20000, 'image' => 'images/kuliner/Nasi Uduk.jpg'],
            ['province_id' => 12, 'name' => 'Batagor', 'description' => 'Bakso tahu goreng dengan bumbu kacang', 'price' => 25000],
            ['province_id' => 12, 'name' => 'Nasi Timbel', 'description' => 'Nasi dibungkus daun pisang dengan lalapan', 'price' => 30000],
            ['province_id' => 12, 'name' => 'Peuyeum', 'description' => 'Singkong fermentasi khas Bandung', 'price' => 15000],
            ['province_id' => 12, 'name' => 'Karedok', 'description' => 'Sayuran mentah dengan bumbu kacang khas Sunda', 'price' => 15000, 'image' => 'images/kuliner/Karedok.jpeg'],
            ['province_id' => 13, 'name' => 'Gudeg', 'description' => 'Nangka muda dimasak dengan santan dan gula Jawa', 'price' => 25000],
            ['province_id' => 13, 'name' => 'Lumpia Semarang', 'description' => 'Lumpia basah atau goreng khas Semarang', 'price' => 20000],
            ['province_id' => 13, 'name' => 'Wingko Babat', 'description' => 'Kue kelapa khas Semarang yang legit', 'price' => 15000],
            ['province_id' => 14, 'name' => 'Gudeg Yogya', 'description' => 'Gudeg khas Jogja yang manis dengan krecek', 'price' => 25000],
            ['province_id' => 14, 'name' => 'Bakpia Pathok', 'description' => 'Kue khas Jogja isi kacang hijau', 'price' => 35000],
            ['province_id' => 14, 'name' => 'Angkringan', 'description' => 'Nasi kucing dengan lauk sederhana', 'price' => 10000],
            ['province_id' => 14, 'name' => 'Sate Klatak', 'description' => 'Sate kambing khas Bantul dengan jeruji besi', 'price' => 25000, 'image' => 'images/kuliner/Sate Klatak.jpg'],
            ['province_id' => 15, 'name' => 'Rawon', 'description' => 'Sup daging dengan kluwek yang hitam pekat', 'price' => 30000, 'image' => 'images/kuliner/rawon_soup_1767578244.png'],
            ['province_id' => 15, 'name' => 'Soto Lamongan', 'description' => 'Soto ayam khas Lamongan', 'price' => 25000],
            ['province_id' => 15, 'name' => 'Lontong Balap', 'description' => 'Lontong dengan tauge, lentho, dan kuah petis', 'price' => 20000],
            ['province_id' => 15, 'name' => 'Rujak Cingur', 'description' => 'Rujak khas Surabaya dengan irisan hidung sapi', 'price' => 20000, 'image' => 'images/kuliner/Rujak Cingur.jpg'],
            ['province_id' => 16, 'name' => 'Sate Bandeng', 'description' => 'Ikan bandeng disuwir dan dibumbui lalu dibakar', 'price' => 35000],
            ['province_id' => 16, 'name' => 'Emping Melinjo', 'description' => 'Kerupuk tipis dari biji melinjo', 'price' => 20000, 'image' => 'images/kuliner/Emping Melinjo.jpg'],
            ['province_id' => 16, 'name' => 'Rabeg', 'description' => 'Gulai daging kambing khas Banten', 'price' => 40000, 'image' => 'images/kuliner/Rabeg.jpg'],
            ['province_id' => 17, 'name' => 'Babi Guling', 'description' => 'Babi utuh dipanggang dengan bumbu khas Bali', 'price' => 50000, 'image' => 'images/kuliner/Babi Guling.jpg'],
            ['province_id' => 17, 'name' => 'Bebek Betutu', 'description' => 'Bebek bumbu rica khas Bali yang pedas', 'price' => 60000, 'image' => 'images/kuliner/Bebek Betutu.webp'],
            ['province_id' => 17, 'name' => 'Lawar', 'description' => 'Sayur campur dengan kelapa dan daging cincang', 'price' => 30000, 'image' => 'images/kuliner/Lawar.jpg'],
            ['province_id' => 17, 'name' => 'Sate Lilit', 'description' => 'Sate lilit ikan khas Bali', 'price' => 25000, 'image' => 'images/kuliner/sate_lilit_bali_1767578247.png'],
            ['province_id' => 18, 'name' => 'Ayam Taliwang', 'description' => 'Ayam bakar pedas khas Lombok', 'price' => 35000, 'image' => 'images/kuliner/Ayam Taliwang.webp'],
            ['province_id' => 18, 'name' => 'Plecing Kangkung', 'description' => 'Kangkung rebus dengan sambal tomat pedas', 'price' => 15000, 'image' => 'images/kuliner/Plecing Kangkung.webp'],
            ['province_id' => 18, 'name' => 'Sate Bulayak', 'description' => 'Sate ayam dengan lontong dari bambu', 'price' => 30000, 'image' => 'images/kuliner/Sate Bulayak.webp'],
            ['province_id' => 19, 'name' => 'Se\'i Sapi', 'description' => 'Daging sapi diasap khas NTT', 'price' => 60000, 'image' => 'images/kuliner/Se\'i.jpeg'],
            ['province_id' => 19, 'name' => 'Jagung Bose', 'description' => 'Jagung rebus dengan kacang merah', 'price' => 20000, 'image' => 'images/kuliner/Jagung Bose.jpg'],
            ['province_id' => 19, 'name' => 'Catemak Jagung', 'description' => 'Bubur jagung khas Rote', 'price' => 15000, 'image' => 'images/kuliner/Catemak Jagung.jpg'],
            ['province_id' => 20, 'name' => 'Bubur Pedas', 'description' => 'Bubur berbumbu rempah khas Sambas', 'price' => 20000, 'image' => 'images/kuliner/Bubur Pedas.jpg'],
            ['province_id' => 20, 'name' => 'Choi Pan', 'description' => 'Kue khas Pontianak isi sayur', 'price' => 15000, 'image' => 'images/kuliner/Choi Pan.jpg'],
            ['province_id' => 20, 'name' => 'Chai Kwe', 'description' => 'Kue kukus khas Tionghoa Kalimantan Barat', 'price' => 15000, 'image' => 'images/kuliner/Chai Kwe.jpg'],
            ['province_id' => 20, 'name' => 'Pengkang', 'description' => 'Masakan ikan asam pedas khas Dayak', 'price' => 35000, 'image' => 'images/kuliner/Pengkang.jpg'],
            ['province_id' => 21, 'name' => 'Juhu Umbut Rotan', 'description' => 'Masakan umbut rotan khas Dayak', 'price' => 30000, 'image' => 'images/kuliner/Juhu Umbut Rotan.jpg'],
            ['province_id' => 21, 'name' => 'Wadi', 'description' => 'Ikan fermentasi khas Dayak', 'price' => 25000, 'image' => 'images/kuliner/Wadi.jpg'],
            ['province_id' => 21, 'name' => 'Kalumpe', 'description' => 'Sayur khas Kalimantan Tengah dari daun singkong', 'price' => 15000, 'image' => 'images/kuliner/Kalumpe.jpg'],
            ['province_id' => 22, 'name' => 'Soto Banjar', 'description' => 'Soto ayam dengan bumbu khas Banjar', 'price' => 25000, 'image' => 'images/kuliner/soto_banjar_1767578250.png'],
            ['province_id' => 22, 'name' => 'Ketupat Kandangan', 'description' => 'Ketupat dengan kuah santan kental', 'price' => 20000, 'image' => 'images/kuliner/Ketupat Kandangan.webp'],
            ['province_id' => 22, 'name' => 'Apam Barabai', 'description' => 'Kue apam khas Barabai yang lembut', 'price' => 15000, 'image' => 'images/kuliner/Apam Barabai.jpg'],
            ['province_id' => 23, 'name' => 'Nasi Bekepor', 'description' => 'Nasi dengan lauk beraneka ragam ala Balik Papan', 'price' => 35000, 'image' => 'images/kuliner/Nasi Bekepor.webp'],
            ['province_id' => 23, 'name' => 'Sate Payau', 'description' => 'Sate rusa khas Kalimantan Timur', 'price' => 40000],
            ['province_id' => 23, 'name' => 'Gence Ruan', 'description' => 'Ikan mas asam manis khas Kutai', 'price' => 45000],
            ['province_id' => 23, 'name' => 'Amplang', 'description' => 'Kerupuk ikan pipih khas Samarinda', 'price' => 25000, 'image' => 'images/kuliner/Amplang.jpeg'],
            ['province_id' => 24, 'name' => 'Kepiting Soka', 'description' => 'Kepiting lunak goreng tepung', 'price' => 50000, 'image' => 'images/kuliner/Kepiting Soka.jpeg'],
            ['province_id' => 24, 'name' => 'Sambal Raja', 'description' => 'Sambal udang segar pedas', 'price' => 35000, 'image' => 'images/kuliner/Sambal Raja.webp'],
            ['province_id' => 24, 'name' => 'Nasi Kuning Khas Tarakan', 'description' => 'Nasi kuning dengan lauk lengkap', 'price' => 30000],
            ['province_id' => 25, 'name' => 'Tinutuan', 'description' => 'Bubur Manado dengan sayuran beraneka ragam', 'price' => 20000],
            ['province_id' => 25, 'name' => 'Cakalang Fufu', 'description' => 'Ikan cakalang asap khas Manado', 'price' => 40000],
            ['province_id' => 25, 'name' => 'Rica-Rica', 'description' => 'Masakan dengan cabai rawit yang sangat pedas', 'price' => 35000, 'image' => 'images/kuliner/Ikan Rica-Rica.jpeg'],
            ['province_id' => 26, 'name' => 'Kaledo', 'description' => 'Sup tulang sapi khas Palu yang gurih', 'price' => 35000, 'image' => 'images/kuliner/Kaledo.webp'],
            ['province_id' => 26, 'name' => 'Uta Kelo', 'description' => 'Sayur keladi khas Kaili', 'price' => 20000, 'image' => 'images/kuliner/Uta Kelo.jpg'],
            ['province_id' => 26, 'name' => 'Lalampa', 'description' => 'Ikan bakar dalam bambu', 'price' => 40000, 'image' => 'images/kuliner/Lalampa.avif'],
            ['province_id' => 26, 'name' => 'Pais', 'description' => 'Ikan dibungkus daun dan dipanggang', 'price' => 35000, 'image' => 'images/kuliner/Pais.jpg'],
            ['province_id' => 27, 'name' => 'Coto Makassar', 'description' => 'Sup jeroan sapi dengan bumbu kacang', 'price' => 30000, 'image' => 'images/kuliner/coto_makassar_1767578245.png'],
            ['province_id' => 27, 'name' => 'Pallubasa', 'description' => 'Sup daging sapi mirip coto tapi lebih kental', 'price' => 35000, 'image' => 'images/kuliner/Pallubasa.jpg'],
            ['province_id' => 27, 'name' => 'Pa\'piong', 'description' => 'Daging dimasak dalam bambu khas Toraja', 'price' => 50000, 'image' => 'images/kuliner/Pa\'piong.webp'],
            ['province_id' => 28, 'name' => 'Kasuami', 'description' => 'Sup ikan khas Buton yang segar', 'price' => 30000, 'image' => 'images/kuliner/Kasuami.jpg'],
            ['province_id' => 28, 'name' => 'Luluta', 'description' => 'Nasi yang dimasak dalam bambu khas Wakatobi', 'price' => 25000, 'image' => 'images/kuliner/Luluta.jpeg'],
            ['province_id' => 28, 'name' => 'Sambal Dabu-Dabu', 'description' => 'Sambal mentah khas Sulawesi', 'price' => 10000, 'image' => 'images/kuliner/Sambal Dabu-Dabu.jpg'],
            ['province_id' => 29, 'name' => 'Binte Biluhuta', 'description' => 'Sup jagung dengan ikan tongkol', 'price' => 25000, 'image' => 'images/kuliner/Binte Biluhuta.webp'],
            ['province_id' => 29, 'name' => 'Ilabulo', 'description' => 'Makanan khas Gorontalo dari sagu dan daging ayam', 'price' => 15000, 'image' => 'images/kuliner/Ilabulo.webp'],
            ['province_id' => 29, 'name' => 'Milu Siram', 'description' => 'Bubur jagung manis', 'price' => 10000, 'image' => 'images/kuliner/Milu Siram.webp'],
            ['province_id' => 30, 'name' => 'Jepa', 'description' => 'Makanan pokok khas Mandar dari sagu atau singkong', 'price' => 35000, 'image' => 'images/kuliner/Jepa.jpg'],
            ['province_id' => 30, 'name' => 'Bau Piapi', 'description' => 'Masakan ikan berkuah kuning khas Mandar', 'price' => 40000, 'image' => 'images/kuliner/Bau Piapi.jpg'],
            ['province_id' => 30, 'name' => 'Apang', 'description' => 'Kue manis khas Mandar', 'price' => 15000, 'image' => 'images/kuliner/Apang.jpg'],
            ['province_id' => 31, 'name' => 'Papeda', 'description' => 'Bubur sagu khas Maluku yang kenyal', 'price' => 20000, 'image' => 'images/kuliner/Papeda.webp'],
            ['province_id' => 31, 'name' => 'Ikan Kuah Pala', 'description' => 'Ikan dengan kuah bumbu pala Banda', 'price' => 40000, 'image' => 'images/kuliner/Ikan Kuah Pala.jpg'],
            ['province_id' => 31, 'name' => 'Kolo-Kolo', 'description' => 'Sambal khas Maluku yang segar', 'price' => 15000, 'image' => 'images/kuliner/Kolo-Kolo.jpg'],
            ['province_id' => 31, 'name' => 'Nasi Lapola', 'description' => 'Nasi khas Maluku dengan kacang tolo dan kelapa', 'price' => 25000, 'image' => 'images/wisata/Nasi Lapola.jpg'],
            ['province_id' => 31, 'name' => 'Ikan Kuah Kei', 'description' => 'Ikan dengan kuah kuning khas kepulauan Kei', 'price' => 35000, 'image' => 'images/kuliner/Ikan Kuah Kei.webp'],
            ['province_id' => 32, 'name' => 'Gohu Ikan', 'description' => 'Ikan mentah bumbu rica khas Ternate', 'price' => 35000, 'image' => 'images/kuliner/Gohu Ikan.webp'],
            ['province_id' => 32, 'name' => 'Nasi Jaha', 'description' => 'Nasi dalam bambu dengan santan', 'price' => 25000, 'image' => 'images/kuliner/Nasi Jaha.jpeg'],
            ['province_id' => 32, 'name' => 'Popeda', 'description' => 'Bubur sagu khas Maluku Utara', 'price' => 20000, 'image' => 'images/kuliner/Papeda.webp'],
            ['province_id' => 33, 'name' => 'Papeda', 'description' => 'Bubur sagu khas Papua yang lengket', 'price' => 20000, 'image' => 'images/kuliner/Papeda.webp'],
            ['province_id' => 33, 'name' => 'Ikan Bakar Manokwari', 'description' => 'Ikan segar dibakar dengan bumbu sederhana', 'price' => 50000, 'image' => 'images/kuliner/Ikan Bakar Manokwari.png'],
            ['province_id' => 33, 'name' => 'Ulat Sagu', 'description' => 'Ulat sagu goreng crispy kaya protein', 'price' => 30000, 'image' => 'images/kuliner/Ulat Sagu.jpg'],
            ['province_id' => 34, 'name' => 'Ikan Kuah Kuning', 'description' => 'Ikan dengan kuah kuning bumbu khas Papua', 'price' => 40000, 'image' => 'images/kuliner/Ikan Kuah Kuning.jpeg'],
            ['province_id' => 34, 'name' => 'Sagu Lempeng', 'description' => 'Sagu tipis dibakar crispy', 'price' => 15000, 'image' => 'images/kuliner/Sagu Lempeng Isi.jpg'],
            ['province_id' => 34, 'name' => 'Ikan Bungkus', 'description' => 'Ikan dibungkus daun lalu dibakar', 'price' => 35000],
            ['province_id' => 35, 'name' => 'Sagu Bakar', 'description' => 'Sagu dipanggang dengan ikan', 'price' => 25000],
            ['province_id' => 35, 'name' => 'Udang Selingkuh', 'description' => 'Udang besar khas Merauke', 'price' => 80000],
            ['province_id' => 35, 'name' => 'Ikan Gabus Kuah', 'description' => 'Ikan gabus dengan kuah bumbu', 'price' => 40000],
            ['province_id' => 35, 'name' => 'Ikan Bakar Arafura', 'description' => 'Ikan bakar khas laut Arafura', 'price' => 50000, 'image' => 'images/kuliner/Ikan Bakar Arafura.jpg'],
            ['province_id' => 36, 'name' => 'Bakar Batu', 'description' => 'Menu lengkap dimasak dengan batu panas', 'price' => 100000, 'image' => 'images/tradisi/bakar-batu-99.png'],
            ['province_id' => 36, 'name' => 'Hipere', 'description' => 'Umbi-umbian khas pegunungan', 'price' => 20000],
            ['province_id' => 36, 'name' => 'Ubi Bakar', 'description' => 'Ubi panggang sederhana tapi lezat', 'price' => 15000, 'image' => 'images/kuliner/Ubi Bakar.jpg'],
            ['province_id' => 37, 'name' => 'Sagu Tumbu', 'description' => 'Sagu dengan sayuran pegunungan', 'price' => 25000, 'image' => 'images/kuliner/Sagu Tumbu.jpg'],
            ['province_id' => 37, 'name' => 'Babi Bakar Batu', 'description' => 'Babi dimasak dengan teknik bakar batu', 'price' => 120000, 'image' => 'images/kuliner/Babi Bakar Batu.jpg'],
            ['province_id' => 37, 'name' => 'Keladi Bakar', 'description' => 'Keladi dipanggang dengan abu', 'price' => 15000, 'image' => 'images/kuliner/Keladi Bakar.jpg'],
            ['province_id' => 38, 'name' => 'Ikan Rica-Rica', 'description' => 'Ikan segar dengan bumbu pedas khas Papua Barat Daya', 'price' => 40000, 'image' => 'images/kuliner/Ikan Rica-Rica.jpeg'],
            ['province_id' => 38, 'name' => 'Sagu Lempeng Isi', 'description' => 'Sagu lempeng dengan isian kelapa atau ikan', 'price' => 25000, 'image' => 'images/kuliner/Sagu Lempeng Isi.jpg'],
            ['province_id' => 38, 'name' => 'Kepiting Soka', 'description' => 'Kepiting cangkang lunak yang digoreng garing', 'price' => 60000, 'image' => 'images/kuliner/Kepiting Soka.jpeg'],
            ['province_id' => 38, 'name' => 'Sagu Gula Merah', 'description' => 'Olahan sagu manis dengan gula aren', 'price' => 15000, 'image' => 'images/kuliner/Sagu Gula Merah.jpg'],
        ];

        foreach ($kulinerData as $data) {
            if (isset($provinces[$data['province_id']])) {
                Kuliner::create($data);
            }
        }
    }
}
